export const REQUEST_AVAILABLE_SITES = "REQUEST_AVAILABLE_SITES";
export const SUCCESS_AVAILABLE_SITES = "SUCCESS_AVAILABLE_SITES";
export const FAIL_AVAILABLE_SITES = "FAIL_AVAILABLE_SITES";

export const REQUEST_MAIN_DATA = "REQUEST_MAIN_DATA";
export const SUCCESS_MAIN_DATA = "SUCCESS_MAIN_DATA";
export const FAIL_MAIN_DATA = "FAIL_MAIN_DATA";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
